service: dynamodb-local
frameworkVersion: '2 || 3'

provider:
  name: aws
  stage: prod
  region: ap-northeast-1
  timeout: 30
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'dynamodb:*'
      Resource:
        - '*'

functions:
  scan:
    handler: handler.scan
    description: DynamoDB Local
    events:
      - http:
          path: /scan
          method: get
          cors: true

plugins:
  - serverless-offline