service: dynamodb-api
frameworkVersion: "2 || 3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: prod
  region: ap-northeast-1
  timeout: 30
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource:
        - "*"

functions:
  access:
    handler: handler.access
    description: AWS SDK for Nodejs DynamoDB sample
    events:
      - http:
          path: access
          method: post
          cors: true
