service: serverless-offline-sample
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.8
  stage: v1
  region: ap-northeast-1
  timeout: 30

functions:
  hello:
    handler: handler.hello
    description: Serverless Framework Offline sample
    events:
      - http:
          path: /test
          method: get

plugins:
  - serverless-offline
